lttng-tools:
        - marker: lttng-tools-2.7
          url: https://github.com/lttng/lttng-tools
          ref: stable-2.7
        - marker: lttng-tools-2.8
          url: https://github.com/lttng/lttng-tools
          ref: stable-2.8
lttng-ust:
        - marker: lttng-ust-2.7
          url: https://github.com/lttng/lttng-ust
          ref: stable-2.7
        - marker: lttng-ust-2.10
          url: https://github.com/lttng/lttng-ust
          ref: stable-2.7

lttng-modules:
        - marker: lttng-modules-2.7
          url: https://github.com/lttng/lttng-modules
          ref: stable-2.7

babeltrace:
        - marker: babeltrace-master
          url: https://github.com/efficios/babeltrace
          ref: master
